### ISSUE TITLE
Add ia and files to public

### ISSUE THREAD

**Issue by arnfinn** [mong/mongts#380]
After #372 

Only sync it to S3 if changed. Separate github actions script, something like this:

```yml
name: Deploy app to AWS
on:
  push:
    branches: [main, develop]
    paths:
      - "apps/skde/public/ia/**"
      - "apps/skde/public/files/**"
  pull_request:
    branches: [main, develop, dependency_updates]
    paths:
      - "apps/skde/public/ia/**"
      - "apps/skde/public/files/**"

jobs:
  deploy_ia_to_S3:
    name: Deploy ia and files to S3
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'eu-west-1'
    steps:
      - name: Set release variables
        if: github.ref == 'refs/heads/main'
        run: |
          echo "s3_bucket=s3://skde.org/helseatlas" >> $GITHUB_ENV
      - name: Set QA variables
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "s3_bucket=s3://qa.skde.org/helseatlas" >> $GITHUB_ENV
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Sync to S3 bucket
        if: github.event_name != 'pull_request'
        run: |
          aws s3 sync apps/public/ia ${{ env.s3_bucket }}/ia --delete --cache-control "public, max-age=1, s-maxage=1"
          aws s3 sync apps/public/files ${{ env.s3_bucket }}/files --delete --cache-control "public, max-age=1, s-maxage=1"
```
